// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: task.proto

package task

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/golang/protobuf/ptypes"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = ptypes.DynamicAny{}
)

// define the regex for a UUID once up-front
var _task_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on Wrapper with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Wrapper) Validate() error {
	if m == nil {
		return nil
	}

	if m.GetMessage() == nil {
		return WrapperValidationError{
			field:  "Message",
			reason: "value is required",
		}
	}

	if v, ok := interface{}(m.GetMessage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return WrapperValidationError{
				field:  "Message",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if m.GetSubmissionTime() == nil {
		return WrapperValidationError{
			field:  "SubmissionTime",
			reason: "value is required",
		}
	}

	return nil
}

// WrapperValidationError is the validation error returned by Wrapper.Validate
// if the designated constraints aren't met.
type WrapperValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e WrapperValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e WrapperValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e WrapperValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e WrapperValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e WrapperValidationError) ErrorName() string { return "WrapperValidationError" }

// Error satisfies the builtin error interface
func (e WrapperValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sWrapper.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = WrapperValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = WrapperValidationError{}

// Validate checks the field values on Message with the rules defined in the
// proto definition for this message. If any rules are violated, an error is returned.
func (m *Message) Validate() error {
	if m == nil {
		return nil
	}

	if l := utf8.RuneCountInString(m.GetTypeName()); l < 1 || l > 256 {
		return MessageValidationError{
			field:  "TypeName",
			reason: "value length must be between 1 and 256 runes, inclusive",
		}
	}

	if len(m.GetRawValue()) > 262144 {
		return MessageValidationError{
			field:  "RawValue",
			reason: "value length must be at most 262144 bytes",
		}
	}

	return nil
}

// MessageValidationError is the validation error returned by Message.Validate
// if the designated constraints aren't met.
type MessageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e MessageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e MessageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e MessageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e MessageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e MessageValidationError) ErrorName() string { return "MessageValidationError" }

// Error satisfies the builtin error interface
func (e MessageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sMessage.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = MessageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = MessageValidationError{}
