// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package task

import (
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Wrapper is a wrapper for task queue payloads.
type Wrapper struct {
	Message              *Message             `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SubmissionTime       *timestamp.Timestamp `protobuf:"bytes,2,opt,name=submission_time,json=submissionTime,proto3" json:"submission_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Wrapper) Reset()         { *m = Wrapper{} }
func (m *Wrapper) String() string { return proto.CompactTextString(m) }
func (*Wrapper) ProtoMessage()    {}
func (*Wrapper) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Wrapper) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Wrapper.Unmarshal(m, b)
}
func (m *Wrapper) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Wrapper.Marshal(b, m, deterministic)
}
func (m *Wrapper) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wrapper.Merge(m, src)
}
func (m *Wrapper) XXX_Size() int {
	return xxx_messageInfo_Wrapper.Size(m)
}
func (m *Wrapper) XXX_DiscardUnknown() {
	xxx_messageInfo_Wrapper.DiscardUnknown(m)
}

var xxx_messageInfo_Wrapper proto.InternalMessageInfo

func (m *Wrapper) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Wrapper) GetSubmissionTime() *timestamp.Timestamp {
	if m != nil {
		return m.SubmissionTime
	}
	return nil
}

// Message is the task message payload.
type Message struct {
	// The canonical protobuf message type name; used for validating the type of the payload.
	//
	// For example: internal.task.v1.Message.
	TypeName string `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	// The protobuf message bytes.
	//
	// Note: we allow 0 byte length for messages with only default field values.
	RawValue             []byte   `protobuf:"bytes,2,opt,name=raw_value,json=rawValue,proto3" json:"raw_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *Message) GetRawValue() []byte {
	if m != nil {
		return m.RawValue
	}
	return nil
}

func init() {
	proto.RegisterType((*Wrapper)(nil), "internal.task.v1.Wrapper")
	proto.RegisterType((*Message)(nil), "internal.task.v1.Message")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x3f, 0x4f, 0x84, 0x30,
	0x18, 0xc6, 0x53, 0x72, 0xc7, 0x9f, 0x6a, 0x94, 0xb0, 0x88, 0x2c, 0x9a, 0x1b, 0xd4, 0xa9, 0x44,
	0x9d, 0x5d, 0xba, 0x9f, 0x03, 0x31, 0x9a, 0xdc, 0x42, 0x5e, 0x62, 0x25, 0x44, 0x0a, 0x4d, 0x5b,
	0xb8, 0xe8, 0xc4, 0xec, 0x17, 0xf0, 0x7b, 0xf8, 0xf1, 0x98, 0x4c, 0x5b, 0x89, 0xc9, 0x6d, 0x6d,
	0x9f, 0xe7, 0x7d, 0x7f, 0xbf, 0x62, 0xac, 0x41, 0xbd, 0x13, 0x21, 0x7b, 0xdd, 0x27, 0x71, 0xd3,
	0x69, 0x26, 0x3b, 0x68, 0x89, 0x7d, 0x1c, 0x6f, 0xb3, 0xb3, 0x11, 0xda, 0xe6, 0x15, 0x34, 0xcb,
	0x97, 0x83, 0xab, 0x66, 0x17, 0x75, 0xdf, 0xd7, 0x2d, 0xcb, 0xed, 0xad, 0x1a, 0xde, 0x72, 0xdd,
	0x70, 0xa6, 0x34, 0x70, 0xe1, 0x0a, 0x9b, 0x6f, 0x84, 0x83, 0x17, 0x09, 0x42, 0x30, 0x99, 0x3c,
	0xe0, 0x80, 0x33, 0xa5, 0xa0, 0x66, 0x29, 0xba, 0x44, 0x37, 0x47, 0x77, 0xe7, 0xe4, 0x90, 0x44,
	0xb6, 0xae, 0x40, 0xc3, 0x99, 0xae, 0xbf, 0x90, 0x17, 0xa3, 0x62, 0x99, 0x49, 0xb6, 0xf8, 0x54,
	0x0d, 0x15, 0x6f, 0x94, 0x6a, 0xfa, 0xae, 0x34, 0xa0, 0xd4, 0xb3, 0x6b, 0x32, 0xe2, 0x2c, 0xc8,
	0x62, 0x41, 0x9e, 0x16, 0x0b, 0xbb, 0xe7, 0x07, 0x79, 0x21, 0x2a, 0x4e, 0xfe, 0x87, 0x4d, 0xbc,
	0xd9, 0xe1, 0xe0, 0x0f, 0x96, 0x5c, 0xe3, 0x48, 0x7f, 0x08, 0x56, 0x76, 0xc0, 0x9d, 0x5a, 0x44,
	0xf1, 0x4c, 0x03, 0xb9, 0x8e, 0x51, 0x3a, 0x79, 0x45, 0x68, 0xc2, 0x47, 0xe0, 0x2c, 0xb9, 0xc2,
	0x91, 0x84, 0x7d, 0x39, 0x42, 0x3b, 0x38, 0xf8, 0x31, 0x8d, 0x66, 0xea, 0x7f, 0xae, 0xd2, 0x69,
	0x8a, 0x8b, 0x50, 0xc2, 0xfe, 0xd9, 0x44, 0xd4, 0xdf, 0xad, 0xcc, 0x87, 0x2a, 0xdf, 0x1a, 0xdd,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x5e, 0xbe, 0x24, 0x5e, 0x01, 0x00, 0x00,
}
